"""RDS Postgres 16 with pgvector.

Pattern note: pgvector is an extension, not a separate database. Postgres
16 ships ready to load it; we enable it via a one-line SQL migration in
Phase 2 (`CREATE EXTENSION vector;`). The HNSW index type is built into
pgvector 0.5+, which is bundled with Postgres 16 on RDS.

DB credentials are auto-generated by CDK and stored in Secrets Manager.
The app reads them at startup via IAM permissions granted in AppRunnerStack.
"""
from __future__ import annotations

from aws_cdk import Duration, RemovalPolicy, Stack
from aws_cdk import aws_ec2 as ec2
from aws_cdk import aws_rds as rds
from constructs import Construct


class DatabaseStack(Stack):
    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        project: str,
        vpc: ec2.IVpc,
        db_security_group: ec2.ISecurityGroup,
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        self.instance = rds.DatabaseInstance(
            self,
            "Postgres",
            engine=rds.DatabaseInstanceEngine.postgres(
                version=rds.PostgresEngineVersion.VER_16_3,
            ),
            instance_type=ec2.InstanceType.of(
                ec2.InstanceClass.BURSTABLE4_GRAVITON,
                ec2.InstanceSize.MICRO,
            ),
            vpc=vpc,
            vpc_subnets=ec2.SubnetSelection(
                subnet_type=ec2.SubnetType.PRIVATE_ISOLATED
            ),
            security_groups=[db_security_group],
            allocated_storage=20,
            max_allocated_storage=50,
            storage_type=rds.StorageType.GP3,
            credentials=rds.Credentials.from_generated_secret(
                username="priorart_pal_app",
                secret_name=f"{project}/db-credentials",
            ),
            database_name="priorart_pal",
            backup_retention=Duration.days(3),
            deletion_protection=False,  # v1: cheap to recreate; flip in prod
            removal_policy=RemovalPolicy.DESTROY,  # v1: don't keep snapshots
            publicly_accessible=False,
            multi_az=False,  # cost: single-AZ is fine for v1
            cloudwatch_logs_exports=["postgresql"],
            cloudwatch_logs_retention=None,
        )

        self.db_endpoint = self.instance.db_instance_endpoint_address
        self.db_credentials_secret = self.instance.secret
